[package]
name = "minigrep"
version = "0.1.0"
edition = "2018"
authors = ["Matt Moeller"]
copyright = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
